### PR TITLE
Add simple user service for systemd.

### PR DESCRIPTION
**Pull request by doronbehar**
Perhaps will it be possible to add it to the AUR package?

### CODE REVIEW

**Comment by jonhoo** [comment]
Thank you! I'd be happy to merge and update the AUR package subject to some tweaks.

Looking at the systemd user service file [for mpd](https://github.com/MusicPlayerDaemon/MPD/blob/master/systemd/user/mpd.service.in), I wonder if we also want to be a bit more paranoid and add a few more restrictions. I believe the following should provide a decent set of rules:
```
ProtectSystem=yes
NoNewPrivileges=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
```
You should also add
```
After=network-online.target
```
To ensure that `hasmail` only starts once the network is accessible.

**Comment by doronbehar** [comment]
You have a point here. If everything works out with those restrictions, I think you should add them :)

**Comment by jonhoo** [comment]
I've actually switched to using [`buzz`](https://github.com/jonhoo/buzz) instead, so it'd be great if you have a chance to test out a modified `systemd` user unit and report back!

**Comment by doronbehar** [comment]
I tested it on my machine and I got the error by systemd saying `hasmail` can't open display. I Google searched on how to start a gui app with systemd and I ran across [this answer in unix.stackexchange](https://unix.stackexchange.com/a/85254/135796). I think It would be best if we will close this PR and leave it as it is.

There is also [this question regarding this problem](https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg).

**Pull request closed without merging**
